### ISSUE TITLE
Repair the BASH ENV variables for Sidekiq synchronization and caching jobs (lib-jobs-staging1)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/lib_jobs#79]
Currently the ENV variables required in order to execute the Sidekiq jobs which read from the ArchivesSpace REST API are not being passed to the Sidekiq process:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/e309c7c3-61d1-4879-89fb-9a859688cbb5)
This should be in place for https://github.com/pulibrary/princeton_ansible/compare/jrgriffiniii-lib_jobs-staging-redis, but these do not seem to be parsed.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/princeton_ansible/compare/jrgriffiniii-lib_jobs-staging-redis is what I had introduced on to the Ansible Role.

**Comment by jrgriffiniii** [comment]
What I am finding on the server is that, in spite of working off of this branch in Ansible, I do not see the Rails ENV variables being parsed:

https://github.com/pulibrary/princeton_ansible/compare/jrgriffiniii-lib_jobs-staging-redis#diff-327b1d1f31381f2168cc20f12aeb9aa098ed43f1e4a8cfc3dd1bb4cf8b25fa46 has
```
rails_app_vars:
  - name: ASPACE_URL
    value: '{{ vault_lib_jobs_staging_aspace_url }}'
  - name: ASPACE_USER
    value: '{{ vault_lib_jobs_staging_aspace_user }}'
  - name: ASPACE_PASSWORD
    value: '{{ vault_lib_jobs_staging_aspace_password }}'
  - name: PULMAP_REDIS_URL
    value: 'localhost'
  - name: PULMAP_REDIS_DB
    value: '0'
```

And on the server, this is set with:

```bash
deploy@lib-jobs-staging1:/opt/lib-jobs$ printenv | grep ASPACE
ASPACE_URL=https://aspace-staging.princeton.edu/staff/api
ASPACE_PASSWORD=$SECRET
ASPACE_USER=$USER
```
